"""create operational events table

Revision ID: 0a027abbf53f
Revises: 7d0121e966b9
Create Date: 2026-07-21 16:55:40.490004
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '0a027abbf53f'
down_revision: str | None = '7d0121e966b9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operational_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('trace_id', sa.String(length=128), nullable=False),
    sa.Column('testcase_id', sa.String(length=128), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=128), nullable=False),
    sa.Column('event_family', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('raw_message', sa.Text(), nullable=False),
    sa.Column('normalized_message', sa.Text(), nullable=False),
    sa.Column('source_line_number', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('protocol_layer', sa.String(length=64), nullable=True),
    sa.Column('direction', sa.String(length=32), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('workflow_stage', sa.String(length=64), nullable=True),
    sa.Column('network_domain', sa.String(length=64), nullable=True),
    sa.Column('operator', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('cause', sa.Text(), nullable=True),
    sa.Column('retry_recommended', sa.Boolean(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('evidence_lines', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('extracted_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_operational_events_event_family', 'operational_events', ['event_family'], unique=False)
    op.create_index('ix_operational_events_event_name', 'operational_events', ['event_name'], unique=False)
    op.create_index('ix_operational_events_severity', 'operational_events', ['severity'], unique=False)
    op.create_index('ix_operational_events_tenant_trace', 'operational_events', ['tenant_id', 'trace_id'], unique=False)
    op.create_index('ix_operational_events_timestamp', 'operational_events', ['timestamp'], unique=False)
    op.create_index('ix_operational_events_trace_sequence', 'operational_events', ['trace_id', 'sequence_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_operational_events_trace_sequence', table_name='operational_events')
    op.drop_index('ix_operational_events_timestamp', table_name='operational_events')
    op.drop_index('ix_operational_events_tenant_trace', table_name='operational_events')
    op.drop_index('ix_operational_events_severity', table_name='operational_events')
    op.drop_index('ix_operational_events_event_name', table_name='operational_events')
    op.drop_index('ix_operational_events_event_family', table_name='operational_events')
    op.drop_table('operational_events')
    # ### end Alembic commands ###
