"""create source artifacts table

Revision ID: 15ef6de8fe59
Revises: ffa284f522ef
Create Date: 2026-07-23 18:29:36.518903
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '15ef6de8fe59'
down_revision: str | None = 'ffa284f522ef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('trace_id', sa.String(length=128), nullable=False),
    sa.Column('testcase_id', sa.String(length=128), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_type', sa.String(length=50), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('artifact_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'artifact_hash', name='uq_source_artifacts_tenant_hash')
    )
    op.create_index('ix_source_artifacts_created_at', 'source_artifacts', ['created_at'], unique=False)
    op.create_index('ix_source_artifacts_status', 'source_artifacts', ['status'], unique=False)
    op.create_index('ix_source_artifacts_tenant_id', 'source_artifacts', ['tenant_id'], unique=False)
    op.create_index('ix_source_artifacts_trace_id', 'source_artifacts', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_source_artifacts_trace_id', table_name='source_artifacts')
    op.drop_index('ix_source_artifacts_tenant_id', table_name='source_artifacts')
    op.drop_index('ix_source_artifacts_status', table_name='source_artifacts')
    op.drop_index('ix_source_artifacts_created_at', table_name='source_artifacts')
    op.drop_table('source_artifacts')
    # ### end Alembic commands ###
