"""create initial tables

Revision ID: 5330ff620be8
Revises: 
Create Date: 2026-07-19 14:33:14.869540
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '5330ff620be8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('trace_id', sa.String(length=128), nullable=False),
    sa.Column('testcase_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'trace_id', name='uq_traces_tenant_trace')
    )
    op.create_index(op.f('ix_traces_status'), 'traces', ['status'], unique=False)
    op.create_index(op.f('ix_traces_tenant_id'), 'traces', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_traces_testcase_id'), 'traces', ['testcase_id'], unique=False)
    op.create_index(op.f('ix_traces_trace_id'), 'traces', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traces_trace_id'), table_name='traces')
    op.drop_index(op.f('ix_traces_testcase_id'), table_name='traces')
    op.drop_index(op.f('ix_traces_tenant_id'), table_name='traces')
    op.drop_index(op.f('ix_traces_status'), table_name='traces')
    op.drop_table('traces')
    # ### end Alembic commands ###
