"""create embedding records table

Revision ID: ffa284f522ef
Revises: 99828d7fe2f2
Create Date: 2026-07-22 17:01:12.734035
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'ffa284f522ef'
down_revision: str | None = '99828d7fe2f2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('trace_id', sa.String(length=255), nullable=False),
    sa.Column('testcase_id', sa.String(length=255), nullable=True),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('model_version', sa.String(length=255), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('content_checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['trace_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'chunk_id', 'model_name', 'model_version', name='uq_embedding_records_tenant_chunk_model_version')
    )
    op.create_index('ix_embedding_records_tenant_chunk', 'embedding_records', ['tenant_id', 'chunk_id'], unique=False)
    op.create_index('ix_embedding_records_tenant_trace', 'embedding_records', ['tenant_id', 'trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(
        "ix_embedding_records_tenant_trace",
        table_name="embedding_records",
    )
    op.drop_index(
        "ix_embedding_records_tenant_chunk",
        table_name="embedding_records",
    )
    op.drop_table("embedding_records")
    # ### end Alembic commands ###
